default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: grails_template_dev
  username: <%= ENV['APP_DB_USERNAME_DEV'] %>
  password: <%= ENV['APP_DB_PASSWORD_DEV'] %>

test:
  <<: *default
  database: grails_template_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
